---
title: "yy2926"
author: "Yuxin"
date: "2018.12.9"
output: github_document
---

```{r}
library(broom)
library(dplyr)
library(tidyverse)
library(patchwork)
library("leaps")
library(faraway)
library(boot)
library(ggplot2)
library("gridExtra")
```

```{r}
raw_data <- read_csv("./Data/Cancer_Registry.csv")
raw_data = janitor::clean_names(raw_data)
raw_data1 = raw_data %>% 
  select(-binned_inc) %>% 
  separate(geography, c("county", "state"), sep = ",") %>% 
  mutate(county = as.factor(county), 
         state = as.factor(state),
         avg_ann_count = avg_ann_count / pop_est2015*100000) %>% 
  select(target_death_rate, avg_ann_count, everything())
```

```{r}
sapply(raw_data1, function(x) sum(is.na(x)))
```

```{r}
## Choose possible variables for our model
raw_data2 = raw_data1 %>% 
  select(target_death_rate, incidence_rate, poverty_percent,  pct_bach_deg25_over, pct_unemployed16_over, pct_public_coverage_alone)
sapply(raw_data2, function(x) sum(is.na(x)))
## No missing values
```

```{r}
## Visualization of predictors to find outliers
histogram1 = ggplot(raw_data2, aes(x  = raw_data2$target_death_rate)) + geom_histogram() + labs(title = "pct_target_death_rate")
histogram2 = ggplot(raw_data2, aes(x  = raw_data2$incidence_rate)) + geom_histogram() + labs(title = "pct_incidence_rate")
histogram3 = ggplot(raw_data2, aes(x  = raw_data2$poverty_percent)) + geom_histogram() + labs(title = "pct_poverty_percent")
histogram4 = ggplot(raw_data2, aes(x  = raw_data2$pct_bach_deg25_over)) + geom_histogram() + labs(title = "pct_pct_bach_deg25_over")
histogram5 = ggplot(raw_data2, aes(x  = raw_data2$pct_unemployed16_over)) + geom_histogram() + labs(title = "pct_unemployed16_over")
histogram6 = ggplot(raw_data2, aes(x  = raw_data2$pct_public_coverage_alone)) + geom_histogram() + labs(title = "pct_public_coverage_alone")
grid.arrange(histogram1, histogram2, histogram3, histogram4, histogram5,histogram6, ncol=2)
histogram1 = ggplot(raw_data2, aes(x  = raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_target_death_rate")
```

```{r}
## dotplot to make outliers more distinct
dot1 = ggplot(raw_data2, aes(x  = raw_data2$target_death_rate, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_target_death_rate")
dot2 = ggplot(raw_data2, aes(x  = raw_data2$incidence_rate, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_incidence_rate")
dot3 = ggplot(raw_data2, aes(x  = raw_data2$poverty_percent, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_poverty_percent")
dot4 = ggplot(raw_data2, aes(x  = raw_data2$pct_bach_deg25_over, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_pct_bach_deg25_over")
dot5 = ggplot(raw_data2, aes(x  = raw_data2$pct_unemployed16_over, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_unemployed16_over")
dot6 = ggplot(raw_data2, aes(x  = raw_data2$pct_public_coverage_alone, y =raw_data2$target_death_rate)) + geom_point() + labs(title = "pct_public_coverage_alone")
grid.arrange(dot1, dot2, dot3, dot4, dot5, dot6, ncol=2)
```